import optuna

PREPROCESS_BG_DATA_COLS = ["potassium", "calcium", "ph", "pco2", "lactate"]
PREPROCESS_LAB_DATA_COLS = [
    "albumin",
    "bun",
    "creatinine",
    "sodium",
    "bicarbonate",
    "platelet",
    "glucose",
    "magnesium",
]
PREPROCESS_VITAL_DATA_COLS = [
    "heartrate",
    "sysbp",
    "diasbp",
    "tempc",
    "resprate",
    "spo2",
]
LSTM_INPUT_SIZE = (
    len(PREPROCESS_BG_DATA_COLS)
    + len(PREPROCESS_LAB_DATA_COLS)
    + len(PREPROCESS_VITAL_DATA_COLS)
)

DEFAULT_WINSORIZE_LOW = "5%"
DEFAULT_WINSORIZE_HIGH = "95%"
DEFAULT_RESAMPLE_INTERPOLATION = "linear"
DEFAULT_RESAMPLE_LIMIT_DIRECTION = "both"

MIN_OBSERVATION_HOURS = 1
MAX_OBSERVATION_HOURS = 48
REQUIRE_EXACT_NUM_HOURS = False
OBSERVATION_WINDOW_START = "intime"

TUNING_LOG_LSTM_HIDDEN_SIZE = (5, 7)
TUNING_LSTM_ACT_OPTIONS = ("ReLU", "Tanh")
TUNING_DROPOUT = (0, 0.5)
TUNING_LOG_FC_HIDDEN_SIZE = (4, 8)
TUNING_FC_ACT_OPTIONS = ("ReLU", "Tanh")
TUNING_OPTIMIZER_OPTIONS = ("Adam", "RMSprop", "SGD")
TUNING_LEARNING_RATE = (1e-5, 1e-1)
TUNING_LOG_BATCH_SIZE = (5, 8)

TUNER_NUM_FOLDS = 5
TUNER_NUM_CV_EPOCHS = 20
TUNER_EPOCHS_PER_FOLD = 5
TUNER_PRUNER_NUM_STARTUP_TRIALS = 5
TUNER_PRUNER_NUM_WARMUP_STEPS = 3
TUNER_NUM_TRIALS = 30
TUNER_KFOLD_RANDOM_SEED = 1234
TUNER_CV_MEAN_METRICS_OF_INTEREST = ("AUC", "validation_loss")
TUNER_PERFORMANCE_METRIC = "validation_loss"
TUNER_OPTIMIZATION_DIRECTION = optuna.study.StudyDirection.MINIMIZE

TRAINER_RANDOM_SEED = 12345678

CV_ASSESSMENT_RANDOM_SEED = 86420
CV_DRIVER_EPOCHS_PER_FOLD = 1000
CV_DRIVER_NUM_FOLDS = 5
CV_DRIVER_EVAL_INTERVAL = 10
CV_DRIVER_EVALS_PER_CHECKPOINT = 1

ATTACK_TUNING_KAPPA = (0.0, 2.0)
ATTACK_TUNING_LAMBDA_1 = (1e-7, 1)
# ATTACK_TUNING_OPTIMIZER_OPTIONS = ("Adam", "RMSprop", "SGD")
ATTACK_TUNING_OPTIMIZER_OPTIONS = ("SGD",)
ATTACK_TUNING_LEARNING_RATE = (1e-5, 1)
ATTACK_TUNING_LOG_BATCH_SIZE = (5, 7)
ATTACK_TUNING_EPOCHS = 1000
ATTACK_TUNING_MAX_NUM_SAMPLES = 520

