from lstm_adversarial_attack.config_paths import DB_DEFAULT_QUERY_DIR

DB_QUERIES = [
    DB_DEFAULT_QUERY_DIR / "icustay_detail.sql",
    DB_DEFAULT_QUERY_DIR / "pivoted_bg.sql",
    DB_DEFAULT_QUERY_DIR / "pivoted_lab.sql",
    DB_DEFAULT_QUERY_DIR / "pivoted_vital.sql",
]

DEFAULT_WINSORIZE_LOW="5%"
DEFAULT_WINSORIZE_HIGH="95%"
DEFAULT_RESAMPLE_INTERPOLATION="linear"
DEFAULT_RESAMPLE_LIMIT_DIRECTION="both"

MIN_OBSERVATION_HOURS = 1
MAX_OBSERVATION_HOURS = 48
REQUIRE_EXACT_NUM_HOURS = False
OBSERVATION_WINDOW_START = "intime"


TUNING_LOG_LSTM_HIDDEN_SIZE = (5, 7)
TUNING_LSTM_ACT_OPTIONS=("ReLU", "Tanh")
TUNING_DROPOUT=(0, 0.5)
TUNING_LOG_FC_HIDDEN_SIZE=(4, 8)
TUNING_FC_ACT_OPTIONS=("ReLU", "Tanh")
TUNING_OPTIMIZER_OPTIONS=("Adam", "RMSprop", "SGD")
TUNING_LEARNING_RATE=(1e-5, 1e-1)
TUNING_LOG_BATCH_SIZE=(5, 8)


